name: Predict Deployment Risk
on: [push]
jobs:
  predict:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start FastAPI server
        run: |
          uvicorn server:app --host 0.0.0.0 --port 8000 &
      
      - name: Wait for FastAPI server to be ready
        run: |
          timeout 30s bash -c 'until curl -s --fail http://127.0.0.1:8000/ > /dev/null; do echo "Waiting for server..."; sleep 1; done'

      - name: Get prediction from FastAPI
        id: prediction
        run: python scripts/get_prediction.py

      - name: Notify on failure prediction
        if: steps.prediction.outputs.prediction == 'high_risk'
        run: python scripts/send_email.py
        env:
          GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          RECIPIENT_EMAIL: 1703313048.it@gmail.com # <-- IMPORTANT: Change this to your email address
          EMAIL_SUBJECT: 'Deployment Risk Prediction: High Risk for ${{ github.repository }}'
          EMAIL_BODY: |
            A high risk of deployment failure was predicted for commit ${{ github.sha }}.

            Please review the changes before deploying.

            Workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Stop FastAPI server
        if: always() # This ensures the server is stopped even if previous steps fail
        run: pkill uvicorn
  
