name: Test FastAPI Endpoint

on:
  push:
    branches:
      - main

jobs:
  test-fastapi:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start FastAPI server
      run: |
        nohup uvicorn server:app --host 127.0.0.1 --port 8000 &
        sleep 5

    - name: Send sample input to FastAPI
      run: |
        echo "Sending sample input to /predict endpoint..."
        python -c "
            import requests
            url = 'http://127.0.0.1:8000/predict'
            payload = {'files_changed': 15, 'test_pass_rate': 0.6, 'build_time_sec': 200}
            response = requests.post(url, json=payload)
            print('Prediction Response:', response.json())"