name: Predict Deployment Risk
on: [push]
jobs:
  predict:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start FastAPI server
        run: |
          uvicorn server:app --host 0.0.0.0 --port 8000 &
      
      - name: Wait for FastAPI server to be ready
        run: |
          timeout 30s bash -c 'until curl -s --fail http://127.0.0.1:8000/ > /dev/null; do echo "Waiting for server..."; sleep 1; done'

      - name: Get prediction from FastAPI
        id: prediction
        run: python scripts/get_prediction.py

      - name: Notify on failure prediction
        if: steps.prediction.outputs.prediction == 'high_risk'
        uses: dawidd6/action-send-gmail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: 'Deployment Risk Prediction: High Risk for ${{ github.repository }}'
          body: |
            A high risk of deployment failure was predicted for commit ${{ github.sha }}.

            Please review the changes before deploying.

            Workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: 1703313048.it@gmail.com # <-- IMPORTANT: Change this to your email address
          from: ${{ secrets.GMAIL_USERNAME }}

      - name: Stop FastAPI server
        if: always() # This ensures the server is stopped even if previous steps fail
        run: pkill uvicorn
  

