name: Predict Deployment Risk
on: [push]
jobs:
  predict:
    runs-on: ubuntu-latest
    steps:
      - name: Send sample input to FastAPI
        run: |
            echo "Sending sample input to /predict endpoint..."
            python3 - <<EOF
            import requests
                url = "http://127.0.0.1:8000/predict"
                payload = {"files_changed": 15, "test_pass_rate": 0.6, "build_time_sec": 200}
                response = requests.post(url, json=payload)
                print("Prediction Response:", response.json())
            EOF