name: Predict Deployment Risk
on: [push]
jobs:
  predict:
    runs-on: ubuntu-latest
    steps:
      - name: Send sample input to FastAPI
        run: |
            echo "Sending sample input to /predict endpoint..."
            python3 predict_test.py